"""
Export Safety Model to C Code for ESP32 Edge Inference
=====================================================
Converts the trained safety_model.joblib (scikit-learn MultiOutputRegressor
with RandomForest) into pure C code using m2cgen.

The generated C function can run on ESP32 with no Python / no network needed.

Usage:
    pip install m2cgen
    python export_model_to_c.py

Output:
    ../ESP32_Setup/include/safety_model.h
"""

import os
import sys
import joblib
import numpy as np

def check_dependencies():
    try:
        import m2cgen
        return True
    except ImportError:
        print("ERROR: m2cgen not installed. Run: pip install m2cgen")
        return False

def retrain_lightweight_model():
    """
    Retrain with fewer estimators (15 trees per output) for ESP32 flash constraints.
    Original model has 100 trees × 2 outputs = large C code.
    15 trees per output keeps accuracy high while fitting in ESP32 4MB flash.
    """
    from sklearn.ensemble import RandomForestRegressor
    from sklearn.multioutput import MultiOutputRegressor
    from sklearn.model_selection import train_test_split
    from sklearn.metrics import mean_squared_error, r2_score

    # Import the same data generation function from training script
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    from train_safety_model import generate_synthetic_data

    print("Generating synthetic data...")
    df = generate_synthetic_data(n_samples=5000)

    X = df[['n_seated', 'n_standing', 'speed_kmh', 'radius_m', 'is_wet', 'gradient_deg', 'dist_to_curve_m']]
    y = df[['risk_score', 'stopping_dist']]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    print("Training lightweight model (8 trees, max_depth=8) for ESP32...")
    model = MultiOutputRegressor(
        RandomForestRegressor(
            n_estimators=8,
            max_depth=8,
            random_state=42
        )
    )
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)
    mse = mean_squared_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)
    print(f"Lightweight Model — MSE: {mse:.4f}, R2: {r2:.4f}")

    # Save lightweight model separately
    lite_path = os.path.join(os.path.dirname(__file__), 'safety_model_lite.joblib')
    joblib.dump(model, lite_path)
    print(f"Saved lightweight model to {lite_path}")

    return model

def export_to_c(model, output_path):
    """Convert model to C code using m2cgen.
    
    MultiOutputRegressor is not directly supported by m2cgen,
    so we export each inner estimator separately and wrap them
    in a single score() function.
    """
    import m2cgen as m2c

    print("Converting model to C code...")

    # MultiOutputRegressor stores individual estimators in .estimators_
    # estimators_[0] = risk_score RF, estimators_[1] = stopping_dist RF
    estimators = model.estimators_
    print(f"  Found {len(estimators)} sub-models to export")

    c_code_risk = m2c.export_to_c(estimators[0])
    c_code_stop = m2c.export_to_c(estimators[1])

    # m2cgen generates a function named 'score' for each — rename them
    c_code_risk = c_code_risk.replace('double score(', 'double score_risk(')
    c_code_stop = c_code_stop.replace('double score(', 'double score_stop(')

    # Wrap in a header file with include guard and documentation
    header = f"""/*
 * AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * 
 * Safety Model for ESP32 Edge Inference
 * Generated by: ML_model_PassP/export_model_to_c.py
 * Model: MultiOutputRegressor(RandomForestRegressor) — exported as 2 sub-models
 * 
 * Input features (double input[7]):
 *   [0] n_seated       - Number of seated passengers (0-55)
 *   [1] n_standing     - Number of standing passengers (0-40)
 *   [2] speed_kmh      - Vehicle speed in km/h (0-80+)
 *   [3] radius_m       - Curve radius in meters (10-200+, larger=straighter)
 *   [4] is_wet         - Road wetness (0.0=dry, 1.0=wet)
 *   [5] gradient_deg   - Road gradient in degrees (-5 to +5)
 *   [6] dist_to_curve_m- Distance to curve in meters (0=at curve)
 * 
 * Output (double output[2]):
 *   [0] risk_score      - Rollover risk (0.0=safe, >0.5=warning, >0.7=critical)
 *   [1] stopping_dist   - Estimated stopping distance in meters
 * 
 * Usage:
 *   double input[7] = {{seats, standing, speed, radius, wet, gradient, dist}};
 *   double output[2];
 *   score(input, output);
 *   double risk = output[0];
 *   double stop_dist = output[1];
 */

#ifndef SAFETY_MODEL_H
#define SAFETY_MODEL_H

// ---- Sub-model 1: Risk Score ----
{c_code_risk}

// ---- Sub-model 2: Stopping Distance ----
{c_code_stop}

// ---- Combined score function (matches ESP32 firmware expectation) ----
static inline void score(double *input, double *output) {{
    output[0] = score_risk(input);
    output[1] = score_stop(input);
}}

#endif /* SAFETY_MODEL_H */
"""

    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w') as f:
        f.write(header)

    file_size_kb = os.path.getsize(output_path) / 1024
    print(f"Generated: {output_path}")
    print(f"File size: {file_size_kb:.1f} KB")

    if file_size_kb > 2000:
        print(f"WARNING: File is {file_size_kb:.0f} KB — may be too large for ESP32 flash (4MB max).")
        print("Consider reducing n_estimators or max_depth.")
    else:
        print("Size is within ESP32 flash limits.")

def validate_model(model):
    """Run a quick sanity check on the model."""
    print("\nValidation — Sample predictions:")

    test_cases = [
        {"label": "Safe (slow, straight)",   "input": [30, 0, 30, 150, 0, 0, 50]},
        {"label": "Moderate (some standing)", "input": [55, 10, 50, 80, 0, 2, 20]},
        {"label": "Risky (fast, tight curve)","input": [55, 30, 70, 25, 1, 3, 0]},
        {"label": "Critical (overloaded)",    "input": [55, 40, 75, 15, 1, 4, 0]},
    ]

    for tc in test_cases:
        inp = np.array([tc["input"]])
        out = model.predict(inp)[0]
        risk = out[0]
        stop = out[1]
        decision = "SAFE" if risk < 0.3 else "CAUTION" if risk < 0.5 else "WARNING" if risk < 0.7 else "CRITICAL"
        print(f"  {tc['label']:<30} → risk={risk:.3f} ({decision}), stop_dist={stop:.1f}m")

def main():
    if not check_dependencies():
        sys.exit(1)

    output_path = os.path.join(
        os.path.dirname(__file__),
        '..', 'ESP32_Setup', 'include', 'safety_model.h'
    )
    output_path = os.path.abspath(output_path)

    # Try loading existing lite model, otherwise retrain
    lite_path = os.path.join(os.path.dirname(__file__), 'safety_model_lite.joblib')
    if os.path.exists(lite_path):
        print(f"Loading existing lightweight model from {lite_path}")
        model = joblib.load(lite_path)
    else:
        print("No lightweight model found. Retraining with reduced trees for ESP32...")
        model = retrain_lightweight_model()

    validate_model(model)
    export_to_c(model, output_path)

    print("\n=== Done! ===")
    print(f"Copy {output_path} is ready for ESP32 compilation.")
    print("Flash the ESP32 firmware and the model runs on-device.")

if __name__ == "__main__":
    main()
